title: JAEMIN JEONG's Homepage
logo: 
description: 강사 정재민 - 데이터사이언스, 파이썬, 진로직업적성
show_downloads: true
google_analytics: G-G3H4KZV2D8

theme: jekyll-theme-time-machine

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
