title: Jaemin Jeong's Homepage
logo: http://github.com/dscoool/dscoool.github.io/raw/main/assets/img/j_logo.png
description: 인공지능/파이썬 강사, 데이터사이언티스트,취업진로지도, 광주과학기술원(GIST)
show_downloads: false
google_analytics: G-G3H4KZV2D8
theme: jekyll-theme-minimal
